id = 6
title = "Cyber Social #1: Cyber Boba Run"
short = "Boba Run" 
date = "Friday 4/29 6:00PM PT"
description = """Want a break from midterms? ğŸ˜©Want to hang out with the coolest cyber crew? ğŸ˜ Join ACM Cyber + Psi Beta Rho in our mid quarter social and midterm stress buster! Weâ€™ll be getting some dinner and boba in Westwood to relax!ğŸ§‹ ğŸ§‹Meet us on Friday, April 29th, 2022 at 6 pm at the Bruin Bear to walk to Westwood! ğŸ¥³Hope to see you there!"""
link = ""
slides = ""
